### ISSUE TITLE
Question/suggestion: !address

### ISSUE THREAD

**Issue by justanotheranonymoususer** [hugsy/windbg_js_scripts#9]
Cool collection! How would you go about implementing `!address`?
i.e. listing the memory map of a process?

**Comment by hugsy** [comment]
As a general process, I'd say by looking into the debugger extensions (in this case the export function `address` in `ext.dll`), but lucky for you @0vercl0k already did something similar you can steal : 
https://github.com/0vercl0k/windbg-scripts/blob/master/telescope/telescope.js#L297

Good luck

**Comment by justanotheranonymoususer** [comment]
> I'd say by looking into the debugger extensions (in this case the export function `address` in `ext.dll`)

I don't think it can necessary help, it uses C++ facilities JS might not have.

> @0vercl0k already did something similar you can steal

As far as I see it doesn't print all of the virtual space, only specific stuff. And requires TTD to print allocated blocks of memory.

I guess it's just not possible with JS. Sad, it's quite basic.

**Comment by hugsy** [comment]
Feel free to report to https://github.com/microsoftfeedback/WinDbg-Feedback

**Comment by justanotheranonymoususer** [comment]
Here
https://github.com/microsoftfeedback/WinDbg-Feedback/issues/52
even though looks like the forum is quite dead
